### PR TITLE
Change flask KonfigProxy to behave like flask config

### PR DESCRIPTION
**Pull request by samarcan**

### CODE REVIEW

**Comment by Stranger6667** [comment]
Seems like we need to fix `mypy` / `pylint` warnings - will work on it now, and let you know when it will be ready to rebase

**Comment by Stranger6667** [comment]
it is ready to rebase :)

**Comment by Stranger6667** [comment]
Please add a changelog entry here - https://github.com/kiwicom/konfetti/blob/master/docs/changelog.rst
Thank you very much for your contribution :)

**Comment by samarcan** [comment]
Done! Thanks to you!

**Pull request merged**
